#!/usr/bin/env bash

selected=$(find ~/personal ~/TEC ~/dotjrr -mindepth 1 -maxdepth 3 -type d | fzf)
if [[ -z "$selected" ]]; then
    exit 0
fi

selected_name=$(basename "$selected" | tr ":., " "____")

switch_to(){
    if [[ -z "$TMUX" ]]; then 
        tmux attach-session -t "$selected_name"
    else
        tmux switch-client -t "$selected_name"
    fi
}

if tmux has-session -t="$selected_name" 2>/dev/null; then
    switch_to
    exit 0
fi

# Crear sesión con ventana yazi en el directorio seleccionado
tmux new-session -d -s "$selected_name" -n yazi  -c "$selected" 'yazi'

# Crear ventana scratch vacía
tmux new-window -t "$selected_name" -n scratch -c "$selected"

# Cambiar o adjuntar a la sesión
switch_to

