#!/usr/bin/env bash

selected=$(find ~/personal ~/ -mindepth 1 -maxdepth 1 -type d | fzf)
if [[ -z "$selected" ]]; then
    exit 0
fi

selected_name=$(basename "$selected" | tr ":., " "____")

switch_to(){
    if [[ -z "$TMUX" ]]; then 
        tmux attach-session -t "$selected_name"
    else
        tmux switch-client -t "$selected_name"
    fi
}

if tmux has-session -t="$selected_name" 2>/dev/null; then
    switch_to
    exit 0
fi

# Crear sesión con ventana nvim en el directorio seleccionado
tmux new-session -d -s "$selected_name" -n nvim "nvim $selected"

# Crear ventana scratch vacía
tmux new-window -t "$selected_name" -n scratch -c "$selected"

# Cambiar o adjuntar a la sesión
switch_to

